# Generated by Django 6.0.3 on 2026-04-10 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_account_tier_trial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stripe_customer_id', models.CharField(db_index=True, max_length=255)),
                ('email', models.EmailField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('active', 'active'), ('recovered', 'recovered'), ('passive_churn', 'passive_churn'), ('fraud_flagged', 'fraud_flagged')], default='active', max_length=30)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.account')),
            ],
            options={
                'db_table': 'core_subscriber',
            },
        ),
        migrations.CreateModel(
            name='SubscriberFailure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_intent_id', models.CharField(max_length=255, unique=True)),
                ('decline_code', models.CharField(max_length=100)),
                ('amount_cents', models.IntegerField()),
                ('payment_method_country', models.CharField(blank=True, max_length=10, null=True)),
                ('failure_created_at', models.DateTimeField()),
                ('classified_action', models.CharField(max_length=50)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.account')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='failures', to='core.subscriber')),
            ],
            options={
                'db_table': 'core_subscriber_failure',
            },
        ),
        migrations.AddConstraint(
            model_name='subscriber',
            constraint=models.UniqueConstraint(fields=('stripe_customer_id', 'account'), name='unique_subscriber_per_account'),
        ),
    ]
