# Generated by Django 6.0.3 on 2026-04-12 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_stripeconnection_unique_stripe_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='company_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
