# Generated by Django 6.0.3 on 2026-04-14 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_add_company_name_to_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='dpa_accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='engine_mode',
            field=models.CharField(blank=True, choices=[('autopilot', 'Autopilot'), ('supervised', 'Supervised')], max_length=20, null=True),
        ),
    ]
