# Generated by Django 6.0.3 on 2026-04-14 19:04

import django_fsm
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_add_dpa_engine_mode_to_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='status',
            field=django_fsm.FSMField(choices=[('active', 'active'), ('recovered', 'recovered'), ('passive_churn', 'passive_churn'), ('fraud_flagged', 'fraud_flagged')], default='active', max_length=30),
        ),
    ]
