# Generated by Django 6.0.3 on 2026-04-14 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_add_dead_letter_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriberfailure',
            name='last_retry_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscriberfailure',
            name='next_retry_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='subscriberfailure',
            name='retry_count',
            field=models.IntegerField(default=0),
        ),
    ]
