# Generated by Django 6.0.3 on 2026-04-14 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_add_retry_tracking_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='last_payment_method_fingerprint',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
