# Generated by Django 6.0.3 on 2026-04-15 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_subscriber_excluded_and_pending_action'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email_type', models.CharField(choices=[('failure_notice', 'Failure Notice'), ('final_notice', 'Final Notice'), ('recovery_confirmation', 'Recovery Confirmation')], max_length=30)),
                ('resend_message_id', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed'), ('suppressed', 'Suppressed')], max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.account')),
                ('failure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_logs', to='core.subscriberfailure')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_logs', to='core.subscriber')),
            ],
            options={
                'db_table': 'core_notification_log',
            },
        ),
        migrations.CreateModel(
            name='NotificationOptOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subscriber_email', models.EmailField(max_length=255)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.account')),
            ],
            options={
                'db_table': 'core_notification_opt_out',
                'constraints': [models.UniqueConstraint(fields=('subscriber_email', 'account'), name='unique_opt_out_per_account')],
            },
        ),
    ]
