# Generated by Django 6.0.3 on 2026-04-25 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_notification_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='notification_tone',
            field=models.CharField(choices=[('professional', 'Professional'), ('friendly', 'Friendly'), ('minimal', 'Minimal')], default='professional', max_length=20),
        ),
    ]
