# Generated by Django 6.0.3 on 2026-04-27 09:04

from django.db import migrations, models


def dedupe_existing_sent_rows(apps, schema_editor):
    """Defensive cleanup: keep the oldest sent NotificationLog per (failure, email_type)
    and drop the rest before the partial unique constraint is added. Pre-existing
    Story 4.1 traffic (failure_notice rows) could otherwise block AddConstraint."""
    NotificationLog = apps.get_model('core', 'NotificationLog')

    duplicates = (
        NotificationLog.objects
        .filter(status='sent')
        .values('failure_id', 'email_type')
        .annotate(n=models.Count('id'))
        .filter(n__gt=1)
    )

    for group in duplicates:
        rows = (
            NotificationLog.objects
            .filter(
                status='sent',
                failure_id=group['failure_id'],
                email_type=group['email_type'],
            )
            .order_by('id')
        )
        keep_id = rows.first().id
        rows.exclude(id=keep_id).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_account_notification_tone'),
    ]

    operations = [
        migrations.RunPython(dedupe_existing_sent_rows, reverse_code=migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='notificationlog',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'sent')), fields=('failure', 'email_type'), name='unique_sent_notification_per_failure_email_type'),
        ),
    ]
